# Generated by Django 5.0.2 on 2024-12-07 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skill', '0003_alter_lesson_options_remove_lesson_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WebDevelopmentCourse',
        ),
    ]
