# Generated by Django 5.0.2 on 2024-12-08 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skill', '0005_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='instructor',
            field=models.CharField(default='Admin', max_length=100),
        ),
        migrations.AlterField(
            model_name='course',
            name='duration',
            field=models.PositiveIntegerField(help_text='Duration in months'),
        ),
    ]
