# Generated by Django 5.0.2 on 2024-12-09 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skill', '0009_remove_course_participants_participant'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Images'),
        ),
        migrations.AddField(
            model_name='course',
            name='short_description',
            field=models.CharField(default='100', max_length=200),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
